services:
  - type: web
    name: apphealth-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: next start -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        value: https://apphealth-frontend.onrender.com
